language: cpp
compiler:
  - gcc
  - clang
  
before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports  # for CMake
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa    # for Qt5
  - sudo apt-get update
  - sudo apt-get install -qq cmake qtbase5-dev
  
before_script:
  - mkdir build
  - cd build
  - export LD_LIBRARY_PATH="../../src:$LD_LIBRARY_PATH"         
  
script:
  - cmake ..
  - make all test
